# Generated by Django 3.2.4 on 2021-06-19 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(upload_to='chocho/images')),
                ('fullName', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=50)),
                ('otp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountmodel')),
            ],
        ),
    ]
