# Generated by Django 3.2.4 on 2021-07-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountmodel_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='phoneNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='accountotp',
            name='phoneNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
