# Generated by Django 3.2.4 on 2021-07-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210701_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroupitem',
            name='phoneNumber',
            field=models.CharField(default='0716351183', max_length=20),
        ),
    ]
