# Generated by Django 3.2.4 on 2021-07-29 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='orderId',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('cb69551c-646d-4fa9-b809-6f2247d0d436'), unique=True),
        ),
    ]
