# Generated by Django 3.2.4 on 2021-07-29 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordermodel_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_date',
            field=models.DateField(default='2021-09-11'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_time',
            field=models.TimeField(default='11:11:11'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='orderId',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('b312215d-928f-483f-b098-19b9e69300b7'), unique=True),
        ),
    ]
