# Generated by Django 3.2.4 on 2021-07-01 23:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordermodel_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='orderId',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('2fbb3351-3fd5-49e6-b96f-0607cfc28e19'), unique=True),
        ),
    ]
