# Generated by Django 3.2.4 on 2021-07-01 23:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_ordermodel_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='orderId',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('4f47e32a-539d-4648-ac78-98274e4a1f35'), unique=True),
        ),
    ]
