# Generated by Django 3.2.4 on 2021-07-02 02:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_ordermodel_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='orderId',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('79df8ef1-6b12-4db4-9413-f9d7b3c146b0'), unique=True),
        ),
    ]
