# Generated by Django 3.2.4 on 2021-07-02 02:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_ordermodel_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='orderId',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('b72b3a10-d147-437c-b8d2-45f56d59ad36'), unique=True),
        ),
    ]
