# Generated by Django 3.2.4 on 2021-07-29 07:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.UUIDField(default=uuid.UUID('0a0bafaf-d269-44c6-857f-66e2c8004b2a'), unique=True)),
                ('image', models.ImageField(max_length=250, upload_to='chocho/productImages')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
                ('cost', models.CharField(max_length=10)),
            ],
        ),
    ]
