# Generated by Django 3.2.4 on 2021-06-19 01:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(auto_created=True, default=uuid.UUID('286caba7-c54e-4afa-a43d-d849718691c9'), unique=True)),
                ('orderName', models.CharField(max_length=250)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.UUIDField(auto_created=True, default=uuid.UUID('4ac43a22-02b3-47a7-8e12-82b2263da5cf'), primary_key=True, serialize=False, unique=True)),
                ('productImage', models.ImageField(max_length=250, upload_to='chocho/productImages')),
                ('productName', models.CharField(max_length=200)),
                ('productDes', models.CharField(max_length=250)),
                ('productCost', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True)),
                ('totalCost', models.FloatField()),
                ('delivered', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ordermodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=250)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ordermodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel')),
            ],
        ),
    ]
