# Generated by Django 3.2.4 on 2021-07-01 23:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField(default=uuid.UUID('7a698630-4354-48ed-8e44-a143a6f07221'), unique=True)),
                ('productImage', models.ImageField(max_length=250, upload_to='chocho/productImages')),
                ('productName', models.CharField(max_length=200)),
                ('productDes', models.CharField(max_length=250)),
                ('productCost', models.CharField(max_length=10)),
            ],
        ),
    ]
