# Generated by Django 3.2.4 on 2021-07-29 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='description',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='productId',
            field=models.UUIDField(default=uuid.UUID('bc01e86a-f9ae-416d-b4a7-d14de16480f4'), unique=True),
        ),
    ]
