# Generated by Django 3.2.4 on 2021-07-01 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('b4359519-9b62-4c9b-b2af-bd984ca54eae'), unique=True),
        ),
    ]
