# Generated by Django 3.2.4 on 2021-07-29 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210729_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='productId',
            field=models.UUIDField(default=uuid.UUID('1457dc53-d5a2-4d15-8d83-c4200e38c1bb'), unique=True),
        ),
    ]
