# Generated by Django 3.2.4 on 2021-07-01 23:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productmodel_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('69df2737-ca80-4d52-89a1-53f1247c2266'), unique=True),
        ),
    ]
