# Generated by Django 3.2.4 on 2021-07-02 02:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productmodel_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('f05c782e-c497-4a86-990f-4a961c944626'), unique=True),
        ),
    ]
