# Generated by Django 3.2.4 on 2021-07-02 02:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productmodel_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='productCost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='productDes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='productImage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='productName',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('bbf243c0-503e-4af3-9f79-f5ca8a1d34b5'), unique=True),
        ),
    ]
