# Generated by Django 3.2.4 on 2021-07-02 02:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210702_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='product_id',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='productId',
            field=models.UUIDField(default=uuid.UUID('cf442fd2-cd2c-4e7e-b971-7e79df600561'), unique=True),
        ),
    ]
